apiVersion: apps/v1
kind: Deployment
metadata:
  name: roy-runtime-transactions
  labels:
    app: transactions
    portWorkload: roy-runtime
spec:
  replicas: 3
  selector:
    matchLabels:
      app: transactions
  template:
    metadata:
      labels:
        app: transactions
    spec:
      containers:
        - name: transactions
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roy-runtime-agent
  labels:
    app: agent
    portWorkload: roy-runtime
spec:
  replicas: 3
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
        - name: agent
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roy-runtime-editor
  labels:
    app: editor
    portWorkload: roy-runtime
spec:
  replicas: 2
  selector:
    matchLabels:
      app: editor
  template:
    metadata:
      labels:
        app: editor
    spec:
      containers:
        - name: editor
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
